# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a94e84e7b3f545aee5e237f9fc07c927aaf5453a3c984d9e2bc28ae2cf4b603867885431b3b6668f635e7b3c4b6f3c6239df569d7bf9e5deea789e52b815d74

test:
  secret_key_base: 61ce0f9392ad5257cd322c8aaa298c18f55d314d1263f3fe9e723b8044dab84b82a3e4a7cd6f139247048b589e0a7f7e816f5e3987ea3af21e1b5c3a3b174270

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
